name: quransada
description: QuranSada - Quran recitation and offline human-voice translations.
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  just_audio: ^0.9.40
  quran: ^1.4.1
  http: ^1.2.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  intl: ^0.20.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/icon/
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/quransada.png
  adaptive_icon_background: "#064E3B"
  adaptive_icon_foreground: assets/icon/quransada.png
